### ISSUE TITLE
Pretrained model is not getting downloaded

### ISSUE THREAD

**Issue by rahulsinghpatel** [rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning#5]
1. when I am cloning this repo that time pre-trained models are not getting downloaded. sometimes it throws an error and sometimes only code get downloaded.
2. if i am trying to download model directly using `wget` or `curl`, then I am getting **not a valid checkpoint** for Segmentation model.
3. even if i am trying downloader to download checkpoint then also i am getting  **not a valid checkpoint** for Segmentation model.

```
Preparing the model ...
WARNING:tensorflow:From /home/centos/miniconda3/envs/tf-tabulo/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Loading model checkpoint weights
WARNING:tensorflow:From /home/centos/miniconda3/envs/tf-tabulo/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "./segmentation/bulk_predict.py", line 50, in <module>
    saver.restore(sess, args.checkpoint_path)
  File "/home/centos/miniconda3/envs/tf-tabulo/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1268, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ../models/segmentation-model/
Finding cells
Error when ruling for 1.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
Error when ruling for Clinical.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


Error when ruling for Clinical.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Error when ruling for P.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Error when ruling for Clinical.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Error when ruling for P.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Error when ruling for Clinical.json | error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Extracting text
Creating csv
Finished
```

so you tell me what is the problem?
OR
can you please upload your models into google drive and share with us?

**Comment by rinkstiekema** [comment]
I've uploaded the models using git LFS (large file system). I'm not sure what goes wrong with the downloading of the model through cloning. I recently cloned the repo myself, and for me it worked correctly.

Regarding the model not being valid, I see it looks into segmentation-model, but should look into segment-model. I'll change the directory name.

**Comment by rahulsinghpatel** [comment]
i have remained segment-model folder to segmentation-model.
Even after renaming back problem is same.

**Comment by rinkstiekema** [comment]
Could you try the pix2pix model instead? I will check if I have uploaded the correct segmentation-model. Sorry for the inconvenience.

**Comment by rahulsinghpatel** [comment]
pix2pix model is working but I want to evaluate the segmentation model.

**Comment by rinkstiekema** [comment]
Thank you for checking. I will check and update the segnet model. I'll let you know in this thread when it is fixed.

**Comment by interviewBubble** [comment]
I am also waiting for the updated segnet model

**Comment by rinkstiekema** [comment]
[This should suffice, I've uploaded the models to google drive](https://drive.google.com/drive/u/0/folders/1dgKISbhBNfR8XXnIxUD_sIhwYNurKHbb
)

**Comment by the-black-knight-01** [comment]
That's COOL!!!!
